name: auto_validate
description: Auto Validate Package
version: 1.0.0
homepage: https://github.com/Mahmoud-ElShenawy/auto_validate

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation:


dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  freezed:
  build_runner:


