name: auto_validate
description: Auto Validate Package. This package will help you to auto validate used regular expressions.
version: 2.0.0-nullsafety.0
homepage: https://github.com/Mahmoud-ElShenawy/auto_validate
repository: https://github.com/Mahmoud-ElShenawy/auto_validate
issue_tracker: https://github.com/Mahmoud-ElShenawy/auto_validate/issues

#  Created By Mahmoud El Shenawy (Dev.Mahmoud.ElShenawy@Gmail.com)


environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  freezed:
  build_runner: